-- Database Schema for SQLite (converted from Oracle DDL)

-- Drop tables if they exist (in reverse dependency order)
DROP TABLE IF EXISTS LIVRO_CATEGORIA;
DROP TABLE IF EXISTS LIVRO_AUTOR;
DROP TABLE IF EXISTS LIVRO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS AUTOR;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS ESTADO;

-- Create ESTADO table
CREATE TABLE ESTADO (
    ID_ESTADO INTEGER PRIMARY KEY AUTOINCREMENT,
    NM_ESTADO TEXT NOT NULL
);

-- Create CIDADE table
CREATE TABLE CIDADE (
    ID_CIDADE INTEGER PRIMARY KEY AUTOINCREMENT,
    NM_CIDADE TEXT NOT NULL,
    ID_ESTADO INTEGER NOT NULL,
    CONSTRAINT CIDADE_ESTADO_FK FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- Create BAIRRO table
CREATE TABLE BAIRRO (
    CEP INTEGER PRIMARY KEY,
    NM_BAIRRO TEXT NOT NULL,
    ID_CIDADE INTEGER NOT NULL,
    CONSTRAINT BAIRRO_CIDADE_FK FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

-- Create USUARIO table
CREATE TABLE USUARIO (
    LOGIN TEXT PRIMARY KEY,
    SENHA TEXT NOT NULL,
    NM_USUARIO TEXT NOT NULL,
    EMAIL_CONTATO TEXT
);

-- Create AUTOR table
CREATE TABLE AUTOR (
    ID_AUTOR INTEGER PRIMARY KEY AUTOINCREMENT,
    NM_AUTOR TEXT NOT NULL
);

-- Create CATEGORIA table
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    NM_CATEGORIA TEXT NOT NULL,
    IMG_CATEGORIA BLOB NOT NULL
);

-- Create LIVRO table
CREATE TABLE LIVRO (
    ID_LIVRO INTEGER PRIMARY KEY AUTOINCREMENT,
    NM_LIVRO TEXT NOT NULL,
    PRECO REAL NOT NULL,
    PAGAMENTO_ELETRONICO TEXT NOT NULL CHECK(PAGAMENTO_ELETRONICO IN ('S', 'N')),
    PAGAMENTO_DINHEIRO TEXT NOT NULL CHECK(PAGAMENTO_DINHEIRO IN ('S', 'N')),
    ENTREGA_PRESENCIAL TEXT NOT NULL CHECK(ENTREGA_PRESENCIAL IN ('S', 'N')),
    ENTREGA_DELIVERY TEXT NOT NULL CHECK(ENTREGA_DELIVERY IN ('S', 'N')),
    IMG_LIVRO BLOB NOT NULL,
    CEP INTEGER NOT NULL,
    LOGIN_COMPRADOR TEXT NOT NULL,
    LOGIN_VENDEDOR TEXT NOT NULL,
    CONSTRAINT LIVRO_BAIRRO_FK FOREIGN KEY(CEP) REFERENCES BAIRRO(CEP),
    CONSTRAINT LIVRO_USUARIO_COMPRADOR_FK FOREIGN KEY(LOGIN_COMPRADOR) REFERENCES USUARIO(LOGIN),
    CONSTRAINT LIVRO_USUARIO_VENDEDOR_FK FOREIGN KEY(LOGIN_VENDEDOR) REFERENCES USUARIO(LOGIN)
);

-- Create LIVRO_AUTOR table (many-to-many relationship)
CREATE TABLE LIVRO_AUTOR (
    ID_AUTOR INTEGER,
    ID_LIVRO INTEGER,
    PRIMARY KEY(ID_AUTOR, ID_LIVRO),
    CONSTRAINT LIVRO_AUTOR_AUTOR_FK FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR),
    CONSTRAINT LIVRO_AUTOR_LIVRO_FK FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(ID_LIVRO)
);

-- Create LIVRO_CATEGORIA table (many-to-many relationship)
CREATE TABLE LIVRO_CATEGORIA (
    ID_CATEGORIA INTEGER,
    ID_LIVRO INTEGER,
    PRIMARY KEY(ID_CATEGORIA, ID_LIVRO),
    CONSTRAINT LIVRO_CATEGORIA_CATEGORIA_FK FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    CONSTRAINT LIVRO_CATEGORIA_LIVRO_FK FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(ID_LIVRO)
);

-- Create indexes for better performance
CREATE INDEX idx_cidade_estado ON CIDADE(ID_ESTADO);
CREATE INDEX idx_bairro_cidade ON BAIRRO(ID_CIDADE);
CREATE INDEX idx_livro_cep ON LIVRO(CEP);
CREATE INDEX idx_livro_comprador ON LIVRO(LOGIN_COMPRADOR);
CREATE INDEX idx_livro_vendedor ON LIVRO(LOGIN_VENDEDOR);
CREATE INDEX idx_livro_autor_livro ON LIVRO_AUTOR(ID_LIVRO);
CREATE INDEX idx_livro_autor_autor ON LIVRO_AUTOR(ID_AUTOR);
CREATE INDEX idx_livro_categoria_livro ON LIVRO_CATEGORIA(ID_LIVRO);
CREATE INDEX idx_livro_categoria_categoria ON LIVRO_CATEGORIA(ID_CATEGORIA);

-- Insert some sample data for testing

-- Estados
INSERT INTO ESTADO (NM_ESTADO) VALUES ('São Paulo');
INSERT INTO ESTADO (NM_ESTADO) VALUES ('Rio de Janeiro');
INSERT INTO ESTADO (NM_ESTADO) VALUES ('Minas Gerais');

-- Cidades
INSERT INTO CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('São Paulo', 1);
INSERT INTO CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Campinas', 1);
INSERT INTO CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Rio de Janeiro', 2);
INSERT INTO CIDADE (NM_CIDADE, ID_ESTADO) VALUES ('Belo Horizonte', 3);

-- Bairros
INSERT INTO BAIRRO (CEP, NM_BAIRRO, ID_CIDADE) VALUES (01310100, 'Centro', 1);
INSERT INTO BAIRRO (CEP, NM_BAIRRO, ID_CIDADE) VALUES (04038001, 'Vila Olímpia', 1);
INSERT INTO BAIRRO (CEP, NM_BAIRRO, ID_CIDADE) VALUES (13010111, 'Centro', 2);
INSERT INTO BAIRRO (CEP, NM_BAIRRO, ID_CIDADE) VALUES (20040020, 'Centro', 3);

-- Usuários
INSERT INTO USUARIO (LOGIN, SENHA, NM_USUARIO, EMAIL_CONTATO) VALUES 
    ('joao123', 'senha123', 'João Silva', 'joao@email.com');
INSERT INTO USUARIO (LOGIN, SENHA, NM_USUARIO, EMAIL_CONTATO) VALUES 
    ('maria456', 'senha456', 'Maria Santos', 'maria@email.com');
INSERT INTO USUARIO (LOGIN, SENHA, NM_USUARIO, EMAIL_CONTATO) VALUES 
    ('pedro789', 'senha789', 'Pedro Oliveira', 'pedro@email.com');

-- Autores
INSERT INTO AUTOR (NM_AUTOR) VALUES ('Machado de Assis');
INSERT INTO AUTOR (NM_AUTOR) VALUES ('Clarice Lispector');
INSERT INTO AUTOR (NM_AUTOR) VALUES ('José de Alencar');
INSERT INTO AUTOR (NM_AUTOR) VALUES ('Paulo Coelho');
INSERT INTO AUTOR (NM_AUTOR) VALUES ('Rick Riodan');

-- Categorias (usando placeholder para imagens)
INSERT INTO CATEGORIA (NM_CATEGORIA, IMG_CATEGORIA) VALUES 
    ('Literatura Brasileira', X'89504E470D0A1A0A0000000D49484452');
INSERT INTO CATEGORIA (NM_CATEGORIA, IMG_CATEGORIA) VALUES 
    ('Romance', X'89504E470D0A1A0A0000000D49484452');
INSERT INTO CATEGORIA (NM_CATEGORIA, IMG_CATEGORIA) VALUES 
    ('Ficção', X'89504E470D0A1A0A0000000D49484452');
INSERT INTO CATEGORIA (NM_CATEGORIA, IMG_CATEGORIA) VALUES 
    ('Autoajuda', X'89504E470D0A1A0A0000000D49484452');

-- Livros
INSERT INTO LIVRO (nm_livro, preco, pagamento_eletronico, pagamento_dinheiro, entrega_presencial, entrega_delivery, img_livro, cep, login_vendedor, LOGIN_COMPRADOR) VALUES 
    ('Percy Jackson', 50.60, 'S', 'S', 'S', 'N', X'89504E470D0A1A0A0000000D49484452', 04038001, "maria456", "pedro789");
INSERT INTO LIVRO (nm_livro, preco, pagamento_eletronico, pagamento_dinheiro, entrega_presencial, entrega_delivery, img_livro, cep, login_vendedor, LOGIN_COMPRADOR) VALUES 
    ('Quincas Borba', 20.13, 'S', 'N', 'S', 'N', X'89504E470D0A1A0A0000000D49484452', 04038001, "pedro789", "maria456");